services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      args:
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb/mysql-data:/var/lib/mariadb
    networks:
      - spring-microservice

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka_server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - spring-microservice

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8762:8762"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - spring-microservice

  account-service:
    container_name: account-service
    build:
      context: ./account_service
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - eureka-server
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: hieudev
      SPRING_DATASOURCE_PASSWORD: password124
      SPRING_APPLICATION_NAME: account-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - spring-microservice

  department-service:
    container_name: department-service
    build:
      context: ./department_service
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - eureka-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: hieudev
      SPRING_DATASOURCE_PASSWORD: password124
      SPRING_APPLICATION_NAME: department-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - spring-microservice

  auth-service:
    container_name: auth-service
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - eureka-server
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: hieudev
      SPRING_DATASOURCE_PASSWORD: password124
      SPRING_APPLICATION_NAME: auth-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - spring-microservice

networks:
  spring-microservice:
    driver: bridge
